name: qr_scanner
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^7.2.1
  camera: ^0.9.4+1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  google_ml_kit: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
